#!/usr/bin/env bash
set -euo pipefail

dry_run="--dry-run"
[[ -n "${1-}" ]] && dry_run=""

rsync -av --delete $dry_run \
  --filter=':- .gitignore' \
  --exclude='.git/' \
  ./ phone-wifi:$TERMUX_HOME/dotfiles/
