#!/usr/bin/env bash

set -euo pipefail

modules=(bash bin config termux)

echo "Stowing dotfiles..."
for module in "${modules[@]}"; do
  if [ -d "$module" ]; then
    echo "-> Stowing $module"
    stow --verbose --target="$HOME" "$module"
  else
    echo "-> Skipping $module (directory not found)"
  fi
done

echo "All done!"
