#!/usr/bin/env bash
set -euo pipefail

REMOVE=false

usage() {
  cat <<EOF
Usage: ${0##*/} [OPTIONS]

Stow the dotfiles

Options:
  -r, --remove    Unlink stowed dotfiles
  -h, --help      Show this help and exit
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -r | --remove)
      shift
      REMOVE=true
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ "$REMOVE" = true ]]; then
  stow --verbose -D -t $HOME */
else
  stow --verbose -t $HOME */
fi

echo "All done!"
