theme = "onedark"

[editor]
scrolloff = 999
auto-info = true
mouse = false
true-color = true
line-number = "relative"
# clipboard-provider = "x-clip"
trim-trailing-whitespace = true
end-of-line-diagnostics = "warning"
color-modes = true

[editor.statusline]
left = [
  "mode",
  "read-only-indicator",
  "file-base-name",
  "file-modification-indicator",
]
center = []
right = ["spinner", "diagnostics", "position", "file-encoding", "file-type"]
diagnostics = ["warning", "error"]

[editor.lsp]
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-q = ":quit"
C-s = ":update"
tab = ":buffer-next"
S-tab = ":buffer-previous"
esc = ["collapse_selection", "keep_primary_selection"]
# Add new line top/bottom
C-j = "add_newline_below"
C-k = "add_newline_above"
# Move line down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# Move line up
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
# Extend multi cursor top/bottom
A-h = "copy_selection_on_prev_line"
A-l = "copy_selection_on_next_line"
# Duplicate line bellow
A-d = ["extend_to_line_bounds", "yank", "paste_after"]
C = "no_op"
A-C = "no_op"
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.select]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
