[[language]]
name = "toml"
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls", "codebook"]

[[language]]
name = "git-commit"
language-servers = ["commit-lsp", "codebook"]

[[language]]
name = "markdown"
language-servers = ["marksman", "codebook"]

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }
language-servers = [
  "emmet",
  "superhtml",
  "codebook",
]

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "css"] }
language-servers = ["vscode-css-language-server", "emmet"]

[[language]]
name = "scss"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "scss"] }
language-servers = ["vscode-css-language-server", "emmet"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "javascript"] }
language-servers = ["typescript-language-server", "codebook"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server", "codebook"]

[[language]]
name = "lua"
auto-format = true
language-servers = ["lua-language-server", "codebook"]

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd", "codebook"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd", "codebook"]

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci"] }
language-servers = ["bash-language-server", "codebook"]

[language-server.lua-language-server.config.Lua]
runtime = { version = "Lua 5.5" }
workspace = { checkThirdParty = "Disable" }

[language-server.emmet]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]
