
[[language]]
name = "go"
language-servers = ["gopls", "codebook"]

[[language]]
name = "text"
scope = "text.md"
file-types = ["txt", "md"]
language-servers = ["codebook"]

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true
language-servers = [
  "vscode-html-language-server",
  "superhtml",
  "emmet",
  "codebook",
]

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "css"] }
language-servers = ["vscode-css-language-server", "emmet"]

[[language]]
name = "scss"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "scss"] }
language-servers = ["vscode-css-language-server", "emmet"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server", "codebook"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server", "codebook"]

[[language]]
name = "lua"
auto-format = true
language-servers = ["lua-language-server", "codebook"]

[[language]]
name = "c"
file-types = ["c", "h"]
auto-format = true
formatter = { command = "clang-format" }
language-servers = ["clangd", "codebook"]

[[language]]
name = "cpp"
file-types = ["cpp", "cc", "cxx", "hpp", "hcc", "hxx"]
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "bash"
formatter = { command = "shfmt", args = ["-i", "2", "-ci"] }
auto-format = true

[[language]]
name = "toml"
auto-format = true

# Language servers

[language-server.lua-language-server.config.Lua.workspace]
# library = [
#   "${env:LLSA}/luaposix",
# ]
checkThirdParty = "Disable"

[language-server.emmet]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]
