set -g mode-keys vi
set -g set-clipboard on
set -g display-time 3000
set -g history-limit 100000
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g base-index 1
setw -g pane-base-index 1

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Tmux config reloaded!"

# Base colors
set -g @bg_color "#1e1e2e"
set -g @fg_color "#cdd6f4"
set -g @active_border "#89b4fa"
set -g @inactive_border "#585b70"
set -g @window_current_bg "#89b4fa"
set -g @window_current_fg "#1e1e2e"
set -g @window_fg "#a6adc8"
set -g @message_fg "#f9e2af"
set -g @time_fg "#fab387"
set -g @date_fg "#f38ba8"

# status bar
set -g status-style "bg=#{@bg_color},fg=#{@fg_color}"
set -g status-left-length 100
set -g status-right-length 100

# Left: session name
set -g status-left "#[fg=#89b4fa,bold] #S #[default]"

# Right: date and time
set -g status-right "#[fg=#{@date_fg}] %m-%d #[fg=#{@time_fg}]%H:%M #[default]"

# Window status
set-window-option -g window-status-style "fg=#{@window_fg},bg=#{@bg_color}"
set-window-option -g window-status-current-style "fg=#{@window_current_fg},bg=#{@window_current_bg},bold"
set -g window-status-format " #[fg=#{@window_fg}]#I:#W#F "
set -g window-status-current-format " #[bg=#{@window_current_bg},fg=#{@window_current_fg}]#I:#W#F "

# Pane borders
set -g pane-border-style "fg=#{@inactive_border}"
set -g pane-active-border-style "fg=#{@active_border}"

# Messages
set -g message-style "bg=#{@bg_color},fg=#{@message_fg}"
set -g message-command-style "bg=#{@bg_color},fg=#{@message_fg}"

# Open panes/windows in current path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# Move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes
bind -r H resize-pane -L 3
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 3

# Kill
bind-key &
kill-window
bind-key x kill-pane

bind-key e new-window -n tmux-edit '
  f="$(mktemp tmux-buffer-XXXXXX.txt)" || exit 1
  tmux capture-pane -p -S - -t ! > "$f"
  "$EDITOR" -- "$f"
  rm -f -- "$f"
'

# clipboard copy
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
# bind-key -T copy-mode y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
