#!/data/data/com.termux/files/usr/bin/env bash

bang() {
  local file="$1"
  local shebang="#!${SHELL%/*}/env ${SHELL##*/}"

  if [[ -z "$file" ]]; then
    echo "Usage: ${FUNCNAME[0]} <file>" >&2
    return 1
  fi

  if [[ ! -f "$file" ]]; then
    touch "$file"
  else
    if [[ "$(file --brief --mime-type "$file")" ~= "text/*"  ]]; then
        echo "'$file' is not a text file" >&2
        return 1
    fi
  fi

  if ! head -n1 "$file" | grep -q '^#!'; then
    sed -i "1i #!$shebang" "$file"
  fi

  chmod u+x "$file"
}



nohistory() {
  set +o history
  HISTFILE=/dev/null
  echo "Everyone suddenly went quiet."
}

function y() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  command yazi "$@" --cwd-file="$tmp"
  IFS= read -r -d '' cwd <"$tmp"
  [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
  rm -f -- "$tmp"
}
