[mgr]
show_hidden = true
show_symlink = true

[opener]
xdg = [{ run = 'xdg-open "$@"', orphan = true }]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "image/*", use = "xdg" },
  { mime = "video/*", use = "xdg" },
  { mime = "audio/*", use = "xdg" },
  { mime = "inode/directory", use = "cd" },
  { mime = "application/json", use = "edit" },
]

[plugin]
prepend_previewers = [
  { mime = "image/*", run = "image" },
  { mime = "video/*", run = "video" },
  { name = "*.dds", run = "magick -define dds:alpha=on" },
  { mime = "image/{avif,heic,jxl,svg+xml}", run = "magick" },
]
