set nocompatible
syntax enable
set hidden

set number
set relativenumber
set numberwidth=1
set signcolumn=no

set ignorecase
set smartcase
set incsearch
set hlsearch

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

set backspace=indent,eol,start
set clipboard=unnamedplus
set undofile
set showcmd
set wildmenu
set ruler
set nosmartindent

nnoremap <C-k> :call append(line('.')-1, '')<CR>
nnoremap <C-j> :call append(line('.'), '')<CR>

